### ISSUE TITLE
顶栏logo字体文件引用时存在跨域问题

### ISSUE THREAD

**Issue by TeaLion** [xiaofeiTM233/bilibili-activity-theme#2]
飞小RAN大佬你好！

我注意到动态左上角的b就一直是个"b"而不是"bilibili"，我就去瞧了一眼控制台与网络内容

控制台报错：
```
Access to font at 'https://【DELETED】/font/Bilibili_Icon.ttf' from origin 'https://t.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://【DELETED】/font/Bilibili_Icon.ttf net::ERR_FAILED
```

网络：
Bilibili_Icon.ttf 请求受到浏览器屏蔽

在确认报错内容后~~ 我顺势去了解了一下CORS到底是个什么玩意， ~~确认为跨域问题，在确认b站其他可用字体使用阿里cdn且含`strict-origin-when-cross-origin`策略的情况下，是否能通过在字体服务器端增加`Accesss-Control-Allow-Origin`策略修复该问题？

以上是假定被屏蔽字体的服务器策略是可修改的情况 我对CORS也只是极其初步的理解，感谢大佬的回复(｀・ω・´)

**Comment by xiaofeiTM233** [comment]
啊原来还是会报跨域吗
我自己这边是正常的所以就没管
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/6c6ddd03-3772-4a16-90d3-3bef00f08c22)
用的是自己的服务器，没套cdn
然后就是刚刚我在我的nginx配置文件里加了跨域了，看看能不能解决？
```
location ~* \.(eot|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}
```

**Comment by xiaofeiTM233** [comment]
当然，通常是不会修改服务端的东西的
这可能是Stylus的问题（详见 https://github.com/openstyles/stylus/issues/1576 ）
你可以通过访问[腾讯文档首页](https://docs.qq.com/)查看样式是否会触发跨域警告，以检验是否是同一问题
若为同一问题，分享一下此问题的解决方案：

1. 关闭Stylus设置中的这两项![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/c218a042-d94e-4d6a-beb3-63bb3ba15690)
2. 更新至最新版Stylus

**Comment by TeaLion** [comment]
拉取了一次更新后logo没有变化，Bilibili Icon仍然报CORS错误

~~然后我突然像是想起了什么一样去清了一次cookie 您猜怎么着~~
顶栏直接变成首页下滑后的nav栏了，同时顶栏的Stylus样式大部分失效，nav栏仅用户头像的阴影仍然生效，但其他动态区域则正常，这时候开关、修改Stylus nav上的样式无法生效
网络选项卡中字体不再能找到Bilibili Icon的请求，因为根本没去请求字体的信息了

~~我合理怀疑b又偷偷改了什么 然后昨天的爆炸事出有因 都是b站干的乆~~

忘了提供浏览器信息了，用的是Google Chrome 115.0.5790.171（正式版本） （64 位），用户代理为 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

以下为动态页nav样式栏局部样式代码
[![pPA9dFH.png](https://s1.ax1x.com/2023/08/05/pPA9dFH.png)](https://imgse.com/i/pPA9dFH)

**Comment by xiaofeiTM233** [comment]
截一下stylus内这两个地方的图
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/21489c85-04a5-4d98-b609-2eee7fa49267)
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/5a205fa2-8fb3-482c-bb6e-52e7826be5ef)

**Comment by TeaLion** [comment]
[![pPACpX6.png](https://s1.ax1x.com/2023/08/05/pPACpX6.png)](https://imgse.com/i/pPACpX6)
[![pPACS6x.png](https://s1.ax1x.com/2023/08/05/pPACS6x.png)](https://imgse.com/i/pPACS6x)

**Comment by xiaofeiTM233** [comment]
奇怪，设置和样式表都没问题，怎么上面那部分没应用上（）
ctrl+f5刷新缓存看看，没见过样式只应用一半的情况

**Comment by TeaLion** [comment]
刷新后不能说毫无差别，只能说一模一样（

**Comment by xiaofeiTM233** [comment]
> 刷新后不能说毫无差别，只能说一模一样（

不清楚怎么个情况，方便的话能否远程控制一下看看？

**Comment by TeaLion** [comment]
好的 已向你的Discord发送了好友请求 ~~qq不是不用但是不好用而且消息太多 还不如discord捏~~
