### ISSUE TITLE
一些小小的样式优先级问题以及字体颜色问题

### ISSUE THREAD

**Issue by misaka10384** [xiaofeiTM233/bilibili-activity-theme#3]
如图 给你框出来了 看看能不能解决一下¿
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/61707010/3b414c11-56e2-4156-aaa5-09f9e581130a)

**Comment by xiaofeiTM233** [comment]
请切换到旧版动态页使用

**Comment by misaka10384** [comment]
> 请切换到旧版动态页使用

旧版顶栏没法亚克力化好像    突然割裂了

**Comment by xiaofeiTM233** [comment]
目前实测旧版动态页正常，如有疑问，请提出，可协助解决
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/59098131-8509-496a-920f-ccc072c4aef5)

**Comment by xiaofeiTM233** [comment]
> 旧版顶栏没法亚克力化好像 突然割裂了

cookie问题，参考readme

**Comment by misaka10384** [comment]
> > 旧版顶栏没法亚克力化好像 突然割裂了
> 
> cookie问题，参考readme

回不去  添加cookie无效果（无法正常添加）  用的EditThisCookie 
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/61707010/44235c66-f009-4a86-ba0e-e94caef3c2bd)

**Comment by misaka10384** [comment]
> > 旧版顶栏没法亚克力化好像 突然割裂了
> 
> cookie问题，参考readme

等等  好怪  之前在动态页切换回旧版再切回新版他不能正常亚克力化顶栏  然后我刷新了一下在切换他又好了    这么看来没事了 感谢
