### ISSUE TITLE
卡顿帧数很低，开硬件加速和关闭模糊没有效果

### ISSUE THREAD

**Issue by Gpan666** [xiaofeiTM233/bilibili-activity-theme#4]
使用的浏览器是chrome beta 版本 122.0.6261.39（正式版本）beta （64 位）  电脑配置不差13400加3060ti之前使用一直不会卡顿，不知道为什么现在会了

**Comment by xiaofeiTM233** [comment]
浏览器硬件加速呢

**Comment by xiaofeiTM233** [comment]
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/2a82cc18-b6dd-4445-9b72-131c0771ebe2)
![image](https://github.com/xiaofeiTM233/bilibili-activity-theme/assets/55832499/22450e71-d227-4b01-aa63-a01b2ab3728b)
可以看看这两个东西吗
1. 第一个图是浏览器任务管理器，Edge的是Shift+Esc打开，主要是看CPU占用
2. 第二个图是Windows任务管理器，主要是看用的哪个显卡

**Comment by Gpan666** [comment]
没事了，我重启了下浏览器不知道为啥好了，怪怪的
