### ISSUE TITLE
无法查看全部设置

### ISSUE THREAD

**Issue by Gpan666** [xiaofeiTM233/bilibili-activity-theme#6]
![QQ20240809-102830](https://github.com/user-attachments/assets/6e7f0fec-4b10-4221-9ad3-e041ee05a3a8)
如图片所示，无法显示全部设置，只能在查看更多插件那里点击配置.

**Comment by xiaofeiTM233** [comment]
这个可能是你自己的问题，看起来是被窗口大小限制了，上下都显示不全……
你用的什么浏览器，Google Chrome？
![image](https://github.com/user-attachments/assets/d5a73b99-9a29-46bc-8be9-6c05ce34dcf6)

**Comment by Gpan666** [comment]
Google Chrome 版本 128.0.6613.27（正式版本）beta （64 位）

**Comment by xiaofeiTM233** [comment]
扩展是从哪里下的，google扩展商店吗

**Comment by xiaofeiTM233** [comment]
![image](https://github.com/user-attachments/assets/d305c49e-ea84-4c5c-80ed-67ad591ffe44)
最新版本仍无法复现，请提供更多信息

**Comment by Gpan666** [comment]
不知道为什么已经正常了
