### ISSUE TITLE
动态页面的背景无法更换

### ISSUE THREAD

**Issue by asd990323** [xiaofeiTM233/bilibili-activity-theme#7]
![PixPin_2024-12-24_09-56-10](https://github.com/user-attachments/assets/e888e6b6-bb5e-4d1d-a35e-f7522c061054)
背景选择其他项了，但更换仍然不生效

**Comment by xiaofeiTM233** [comment]
暂不支持新版动态页，请点击回到旧版

**Comment by asd990323** [comment]
好吧，谢谢了

________________________________
发件人: ***@***.*** ***@***.***> 代表 飞小RAN ***@***.***>
发送时间: 2024年12月24日 13:08
收件人: xiaofeiTM233/bilibili-newsfeed-theme ***@***.***>
抄送: asd990323 ***@***.***>; Author ***@***.***>
主题: Re: [xiaofeiTM233/bilibili-newsfeed-theme] 动态页面的背景无法更换 (Issue #7)


暂不支持新版动态页，请点击回到旧版

―
